context:
  version: 3.6.4

package:
  name: scala3
  version: ${{ version }}

source:
  git: https://github.com/lampepfl/dotty
  tag: ${{ version }}

build:
  number: 0
  noarch: generic

requirements:
  build:
    - findutils
    - maven
    - sbt
    - sed
    - openjdk >=17,<18
  run:
    - openjdk

tests:
  - script:
      - scala --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - target/generated-resources/licenses/
  summary: The Scala 3 compiler, also known as Dotty.
  homepage: https://dotty.epfl.ch
  repository: https://github.com/lampepfl/dotty

extra:
  recipe-maintainers:
    - danielnachun
